// metadata.ts

export const metadata = {
  title: 'ferdiyan',
  description: 'Generated by create next app',
};

export const updateMetadata = (title, description) => {
  metadata.title = title;
  metadata.description = description;
};
